name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Generate Grpc files
        run: npm run generate
      - name: Test
        shell: bash
        run: |
          npm run test -- --run
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Format Check
        shell: bash
        run: |
          npm run format-check
      - name: Check Lint
        shell: bash
        run: |
          npm run lint